/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.pbd.view;

import java.awt.Color;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JTextField;

/**
 *
 * @author Glenda Alves de Lima
 */
public class BuscarAlunos extends javax.swing.JInternalFrame {
    
    private JButton btnEd, btnEx, btnMen, btnAcom, btnAgen;
    private Icon Iconedita, Iconexcluir, Iconmensalidade, Iconacompanhamento, Iconagenda;

    /**
     * Creates new form BuscarAlunos
     */
    public BuscarAlunos() {
        initComponents();
        Iconedita = new ImageIcon(getClass().getResource("/br/com/pbd/resource/editarr.png"));
        Iconexcluir = new ImageIcon(getClass().getResource("/br/com/pbd/resource/Exclui.png"));
        Iconmensalidade = new ImageIcon(getClass().getResource("/br/com/pbd/resource/mensalidade.png"));
        Iconacompanhamento = new ImageIcon(getClass().getResource("/br/com/pbd/resource/acompanhamento.png"));
        Iconagenda = new ImageIcon(getClass().getResource("/br/com/pbd/resource/calendarior.png"));

        btnEd = new JButton(getIconedita());
        btnEd.setName("editar");
        btnEd.setBorder(null);
        btnEd.setContentAreaFilled(false);

        btnEx = new JButton(getIconexcluir());
        btnEx.setName("Excluir");
        btnEx.setBorder(null);
        btnEx.setContentAreaFilled(false);

        btnMen = new JButton(getIconmensalidade());
        btnMen.setName("mensalidade");
        btnMen.setBorder(null);
        btnMen.setContentAreaFilled(false);

        btnAcom = new JButton(getIconacompanhamento());
        btnAcom.setName("acompanhamento");
        btnAcom.setBorder(null);
        btnAcom.setContentAreaFilled(false);

        btnAgen = new JButton(getIconagenda());
        btnAgen.setName("agenda");
        btnAgen.setBorder(null);
        btnAgen.setContentAreaFilled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        labelcadastro = new javax.swing.JLabel();
        botaoAdicionar = new javax.swing.JButton();
        botaoFechar = new javax.swing.JButton();
        label1 = new java.awt.Label();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaAlunos = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtpesquisa = new br.com.pbd.modelos.JTextFieldHint(new JTextField(), "pesquisar", " Pesquise por Nome CPF ou RG ");

        setPreferredSize(new java.awt.Dimension(962, 739));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel7.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 946, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 9, Short.MAX_VALUE)
        );

        labelcadastro.setFont(new java.awt.Font("Felix Titling", 0, 24)); // NOI18N
        labelcadastro.setForeground(new java.awt.Color(0, 102, 102));
        labelcadastro.setText("Buscar DE Aluno");

        botaoAdicionar.setBackground(new java.awt.Color(255, 255, 255));
        botaoAdicionar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        botaoAdicionar.setForeground(new java.awt.Color(0, 102, 102));
        botaoAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/pbd/resource/plus (1).png"))); // NOI18N
        botaoAdicionar.setText("Adicionar");
        botaoAdicionar.setBorderPainted(false);
        botaoAdicionar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botaoAdicionarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botaoAdicionarMouseExited(evt);
            }
        });
        botaoAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAdicionarActionPerformed(evt);
            }
        });

        botaoFechar.setBackground(new java.awt.Color(255, 255, 255));
        botaoFechar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        botaoFechar.setForeground(new java.awt.Color(0, 102, 102));
        botaoFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/pbd/resource/Cancela.png"))); // NOI18N
        botaoFechar.setText("Fechar");
        botaoFechar.setBorderPainted(false);
        botaoFechar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botaoFecharMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botaoFecharMouseExited(evt);
            }
        });
        botaoFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoFecharActionPerformed(evt);
            }
        });

        label1.setText("Pesquisar :");

        tabelaAlunos.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tabelaAlunos.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tabelaAlunos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nome ", "Situação", "CPF", "RG"
            }
        ));
        tabelaAlunos.setRowHeight(30);
        tabelaAlunos.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tabelaAlunos);

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        jLabel1.setFont(new java.awt.Font("DeVinne Txt BT", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Lista de Alunos Matriculados");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, 0))
        );

        txtpesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpesquisaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtpesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 534, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(botaoAdicionar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(botaoFechar))
                            .addComponent(labelcadastro))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelcadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(botaoAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(botaoFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(txtpesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoAdicionarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoAdicionarMouseEntered
        getBotaoAdicionar().setBackground(new Color(204, 204, 204)); // cor de fundo quando aparece
        getBotaoAdicionar().setForeground(new Color(255, 255, 255)); // cor da letra quando aparece
    }//GEN-LAST:event_botaoAdicionarMouseEntered

    private void botaoAdicionarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoAdicionarMouseExited
        getBotaoAdicionar().setBackground(new Color(255, 255, 255));// Fundo Quando Solta
        getBotaoAdicionar().setForeground(new Color(0, 102, 102));// letra quando solta cor
    }//GEN-LAST:event_botaoAdicionarMouseExited

    private void botaoAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAdicionarActionPerformed

    }//GEN-LAST:event_botaoAdicionarActionPerformed

    private void botaoFecharMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoFecharMouseEntered
        getBotaoFechar().setBackground(new Color(204, 204, 204)); // cor de fundo quando aparece
        getBotaoFechar().setForeground(new Color(255, 255, 255)); // cor da letra quando aparece
    }//GEN-LAST:event_botaoFecharMouseEntered

    private void botaoFecharMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoFecharMouseExited
        getBotaoFechar().setBackground(new Color(255, 255, 255));// Fundo Quando Solta
        getBotaoFechar().setForeground(new Color(0, 102, 102));// letra quando solta cor
    }//GEN-LAST:event_botaoFecharMouseExited

    private void botaoFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoFecharActionPerformed
        setVisible(false);

    }//GEN-LAST:event_botaoFecharActionPerformed

    private void txtpesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpesquisaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoAdicionar;
    private javax.swing.JButton botaoFechar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.Label label1;
    private javax.swing.JLabel labelcadastro;
    private javax.swing.JTable tabelaAlunos;
    private javax.swing.JTextField txtpesquisa;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the btnEd
     */
    public JButton getBtnEd() {
        return btnEd;
    }

    /**
     * @param btnEd the btnEd to set
     */
    public void setBtnEd(JButton btnEd) {
        this.btnEd = btnEd;
    }

    /**
     * @return the btnEx
     */
    public JButton getBtnEx() {
        return btnEx;
    }

    /**
     * @param btnEx the btnEx to set
     */
    public void setBtnEx(JButton btnEx) {
        this.btnEx = btnEx;
    }

    /**
     * @return the btnMen
     */
    public JButton getBtnMen() {
        return btnMen;
    }

    /**
     * @param btnMen the btnMen to set
     */
    public void setBtnMen(JButton btnMen) {
        this.btnMen = btnMen;
    }

    /**
     * @return the btnAcom
     */
    public JButton getBtnAcom() {
        return btnAcom;
    }

    /**
     * @param btnAcom the btnAcom to set
     */
    public void setBtnAcom(JButton btnAcom) {
        this.btnAcom = btnAcom;
    }

    /**
     * @return the btnAgen
     */
    public JButton getBtnAgen() {
        return btnAgen;
    }

    /**
     * @param btnAgen the btnAgen to set
     */
    public void setBtnAgen(JButton btnAgen) {
        this.btnAgen = btnAgen;
    }

    /**
     * @return the Iconedita
     */
    public Icon getIconedita() {
        return Iconedita;
    }

    /**
     * @param Iconedita the Iconedita to set
     */
    public void setIconedita(Icon Iconedita) {
        this.Iconedita = Iconedita;
    }

    /**
     * @return the Iconexcluir
     */
    public Icon getIconexcluir() {
        return Iconexcluir;
    }

    /**
     * @param Iconexcluir the Iconexcluir to set
     */
    public void setIconexcluir(Icon Iconexcluir) {
        this.Iconexcluir = Iconexcluir;
    }

    /**
     * @return the Iconmensalidade
     */
    public Icon getIconmensalidade() {
        return Iconmensalidade;
    }

    /**
     * @param Iconmensalidade the Iconmensalidade to set
     */
    public void setIconmensalidade(Icon Iconmensalidade) {
        this.Iconmensalidade = Iconmensalidade;
    }

    /**
     * @return the Iconacompanhamento
     */
    public Icon getIconacompanhamento() {
        return Iconacompanhamento;
    }

    /**
     * @param Iconacompanhamento the Iconacompanhamento to set
     */
    public void setIconacompanhamento(Icon Iconacompanhamento) {
        this.Iconacompanhamento = Iconacompanhamento;
    }

    /**
     * @return the Iconagenda
     */
    public Icon getIconagenda() {
        return Iconagenda;
    }

    /**
     * @param Iconagenda the Iconagenda to set
     */
    public void setIconagenda(Icon Iconagenda) {
        this.Iconagenda = Iconagenda;
    }

    /**
     * @return the botaoAdicionar
     */
    public javax.swing.JButton getBotaoAdicionar() {
        return botaoAdicionar;
    }

    /**
     * @param botaoAdicionar the botaoAdicionar to set
     */
    public void setBotaoAdicionar(javax.swing.JButton botaoAdicionar) {
        this.botaoAdicionar = botaoAdicionar;
    }

    /**
     * @return the botaoFechar
     */
    public javax.swing.JButton getBotaoFechar() {
        return botaoFechar;
    }

    /**
     * @param botaoFechar the botaoFechar to set
     */
    public void setBotaoFechar(javax.swing.JButton botaoFechar) {
        this.botaoFechar = botaoFechar;
    }

    /**
     * @return the jLabel1
     */
    public javax.swing.JLabel getjLabel1() {
        return jLabel1;
    }

    /**
     * @param jLabel1 the jLabel1 to set
     */
    public void setjLabel1(javax.swing.JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    /**
     * @return the jPanel1
     */
    public javax.swing.JPanel getjPanel1() {
        return jPanel1;
    }

    /**
     * @param jPanel1 the jPanel1 to set
     */
    public void setjPanel1(javax.swing.JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    /**
     * @return the jPanel2
     */
    public javax.swing.JPanel getjPanel2() {
        return jPanel2;
    }

    /**
     * @param jPanel2 the jPanel2 to set
     */
    public void setjPanel2(javax.swing.JPanel jPanel2) {
        this.jPanel2 = jPanel2;
    }

    /**
     * @return the jPanel7
     */
    public javax.swing.JPanel getjPanel7() {
        return jPanel7;
    }

    /**
     * @param jPanel7 the jPanel7 to set
     */
    public void setjPanel7(javax.swing.JPanel jPanel7) {
        this.jPanel7 = jPanel7;
    }

    /**
     * @return the jScrollPane1
     */
    public javax.swing.JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    /**
     * @param jScrollPane1 the jScrollPane1 to set
     */
    public void setjScrollPane1(javax.swing.JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    /**
     * @return the label1
     */
    public java.awt.Label getLabel1() {
        return label1;
    }

    /**
     * @param label1 the label1 to set
     */
    public void setLabel1(java.awt.Label label1) {
        this.label1 = label1;
    }

    /**
     * @return the labelcadastro
     */
    public javax.swing.JLabel getLabelcadastro() {
        return labelcadastro;
    }

    /**
     * @param labelcadastro the labelcadastro to set
     */
    public void setLabelcadastro(javax.swing.JLabel labelcadastro) {
        this.labelcadastro = labelcadastro;
    }

    /**
     * @return the tabelaAlunos
     */
    public javax.swing.JTable getTabelaAlunos() {
        return tabelaAlunos;
    }

    /**
     * @param tabelaAlunos the tabelaAlunos to set
     */
    public void setTabelaAlunos(javax.swing.JTable tabelaAlunos) {
        this.tabelaAlunos = tabelaAlunos;
    }

    /**
     * @return the txtpesquisa
     */
    public javax.swing.JTextField getTxtpesquisa() {
        return txtpesquisa;
    }

    /**
     * @param txtpesquisa the txtpesquisa to set
     */
    public void setTxtpesquisa(javax.swing.JTextField txtpesquisa) {
        this.txtpesquisa = txtpesquisa;
    }

    

}
