/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.pbd.view;

import br.com.pbd.modelos.ContaaPagar;
import java.awt.Color;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JTextField;

/**
 *
 * @author Glenda Alves de Lima
 */
public class Despesas extends javax.swing.JInternalFrame {

    /**
     * Creates new form ContaaPagar
     */
      private Icon Iconeditar, Iconexcluir;
    private JButton btnEx, btnEd;
    private JButton btnPag;
    private Icon Iconpagar;
    public Despesas() {
        initComponents();
        Iconeditar = new ImageIcon(getClass().getResource("/br/com/pbd/resource/editarr.png"));
        Iconexcluir = new ImageIcon(getClass().getResource("/br/com/pbd/resource/Exclui.png"));
        Iconpagar = new ImageIcon(getClass().getResource("/br/com/pbd/resource/o.png"));

        btnPag = new JButton(getIconpagar());
        btnPag.setName("pagar");
        btnPag.setBorder(null);
        btnPag.setContentAreaFilled(false);

        btnEd = new JButton(getIconeditar());
        btnEd.setName("editar");
        btnEd.setBorder(null);
        btnEd.setContentAreaFilled(false);

        btnEx = new JButton(getIconexcluir());
        btnEx.setName("excluir");
        btnEx.setBorder(null);
        btnEx.setContentAreaFilled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelcadastro2 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        panelContas = new javax.swing.JPanel();
        label2 = new java.awt.Label();
        descricaoConta = new javax.swing.JTextField();
        label3 = new java.awt.Label();
        dataemissaoconta = new com.toedter.calendar.JDateChooser();
        label4 = new java.awt.Label();
        datavencimentoconta = new com.toedter.calendar.JDateChooser();
        label5 = new java.awt.Label();
        valorconta = new javax.swing.JTextField();
        botaoSalvarconta = new javax.swing.JButton();
        label14 = new java.awt.Label();
        combotipo = new javax.swing.JComboBox<>();
        combopagamento = new javax.swing.JComboBox<>();
        label15 = new java.awt.Label();
        botaoCancelar = new javax.swing.JButton();
        label6 = new java.awt.Label();
        txtPesquisa = new br.com.pbd.modelos.JTextFieldHint(new JTextField(), "pesquisar", " Pesquise por Descrição  ");
        botaoadicionar = new javax.swing.JButton();
        botaoFechar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaconta = new javax.swing.JTable();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        labelcadastro2.setFont(new java.awt.Font("Felix Titling", 0, 24)); // NOI18N
        labelcadastro2.setForeground(new java.awt.Color(0, 102, 102));
        labelcadastro2.setText("despesas");

        jPanel9.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 9, Short.MAX_VALUE)
        );

        panelContas.setBackground(new java.awt.Color(255, 255, 255));
        panelContas.setBorder(javax.swing.BorderFactory.createTitledBorder("Contas"));

        label2.setText("Descricao :");

        label3.setText("Data de Emissão :");

        label4.setText("Data Vencimento");

        label5.setText("Valor :");

        botaoSalvarconta.setBackground(new java.awt.Color(255, 255, 255));
        botaoSalvarconta.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        botaoSalvarconta.setForeground(new java.awt.Color(0, 102, 102));
        botaoSalvarconta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/pbd/resource/Salva.png"))); // NOI18N
        botaoSalvarconta.setText("Salvar");
        botaoSalvarconta.setBorderPainted(false);
        botaoSalvarconta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botaoSalvarcontaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botaoSalvarcontaMouseExited(evt);
            }
        });

        label14.setText("Tipo :");

        combotipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "credito", "debito" }));

        combopagamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "dinheiro", "cheque", "cartâo" }));

        label15.setText("Forma de Pagamento :");

        botaoCancelar.setBackground(new java.awt.Color(255, 255, 255));
        botaoCancelar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        botaoCancelar.setForeground(new java.awt.Color(0, 102, 102));
        botaoCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/pbd/resource/Cancela.png"))); // NOI18N
        botaoCancelar.setText("Cancelar");
        botaoCancelar.setBorderPainted(false);
        botaoCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botaoCancelarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botaoCancelarMouseExited(evt);
            }
        });
        botaoCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelContasLayout = new javax.swing.GroupLayout(panelContas);
        panelContas.setLayout(panelContasLayout);
        panelContasLayout.setHorizontalGroup(
            panelContasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContasLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(panelContasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelContasLayout.createSequentialGroup()
                        .addGroup(panelContasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(descricaoConta, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46)
                        .addGroup(panelContasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dataemissaoconta, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelContasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(datavencimentoconta, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(panelContasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(valorconta, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelContasLayout.createSequentialGroup()
                        .addGroup(panelContasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(combotipo, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(60, 60, 60)
                        .addGroup(panelContasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelContasLayout.createSequentialGroup()
                                .addComponent(label15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(panelContasLayout.createSequentialGroup()
                                .addComponent(combopagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(64, 64, 64)
                                .addComponent(botaoSalvarconta)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(38, 38, 38)
                        .addComponent(botaoCancelar)
                        .addGap(36, 36, 36)))
                .addContainerGap())
        );
        panelContasLayout.setVerticalGroup(
            panelContasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelContasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelContasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(descricaoConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dataemissaoconta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(datavencimentoconta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valorconta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelContasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(panelContasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelContasLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(panelContasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(combotipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(combopagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelContasLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelContasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botaoSalvarconta)
                            .addComponent(botaoCancelar))
                        .addContainerGap())))
        );

        label6.setText("Pesquisar :");

        txtPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesquisaActionPerformed(evt);
            }
        });

        botaoadicionar.setBackground(new java.awt.Color(255, 255, 255));
        botaoadicionar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        botaoadicionar.setForeground(new java.awt.Color(0, 102, 102));
        botaoadicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/pbd/resource/plus (1).png"))); // NOI18N
        botaoadicionar.setText("Adicionar");
        botaoadicionar.setBorderPainted(false);
        botaoadicionar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botaoadicionarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botaoadicionarMouseExited(evt);
            }
        });
        botaoadicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoadicionarActionPerformed(evt);
            }
        });

        botaoFechar.setBackground(new java.awt.Color(255, 255, 255));
        botaoFechar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        botaoFechar.setForeground(new java.awt.Color(0, 102, 102));
        botaoFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/pbd/resource/Cancela.png"))); // NOI18N
        botaoFechar.setText("Fechar");
        botaoFechar.setBorderPainted(false);
        botaoFechar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botaoFecharMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botaoFecharMouseExited(evt);
            }
        });
        botaoFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoFecharActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));

        jLabel2.setFont(new java.awt.Font("DeVinne Txt BT", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Contas a Pagar");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 934, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 0, 0))
        );

        tabelaconta.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tabelaconta.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tabelaconta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tabelaconta.setFocusable(false);
        tabelaconta.setRowHeight(30);
        tabelaconta.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tabelaconta);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(botaoadicionar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botaoFechar)
                        .addGap(71, 71, 71))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelContas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelcadastro2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(labelcadastro2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelContas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botaoadicionar)
                            .addComponent(botaoFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 108, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCancelarActionPerformed
    
    }//GEN-LAST:event_botaoCancelarActionPerformed

    private void botaoCancelarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoCancelarMouseExited
        getBotaoCancelar().setBackground(new Color(255, 255, 255));// Fundo Quando Solta
        getBotaoCancelar().setForeground(new Color(0, 102, 102));// letra quando solta cor
    }//GEN-LAST:event_botaoCancelarMouseExited

    private void botaoCancelarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoCancelarMouseEntered
        getBotaoCancelar().setBackground(new Color(204, 204, 204)); // cor de fundo quando aparece
        getBotaoCancelar().setForeground(new Color(255, 255, 255)); // cor da letra quando aparece
    }//GEN-LAST:event_botaoCancelarMouseEntered

    private void botaoSalvarcontaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoSalvarcontaMouseExited
        getBotaoSalvarconta().setBackground(new Color(255, 255, 255));// Fundo Quando Solta
        getBotaoSalvarconta().setForeground(new Color(0, 102, 102));// letra quando solta cor
    }//GEN-LAST:event_botaoSalvarcontaMouseExited

    private void botaoSalvarcontaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoSalvarcontaMouseEntered
        getBotaoSalvarconta().setBackground(new Color(204, 204, 204)); // cor de fundo quando aparece
        getBotaoSalvarconta().setForeground(new Color(255, 255, 255)); // cor da letra quando aparece
    }//GEN-LAST:event_botaoSalvarcontaMouseEntered

    private void txtPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesquisaActionPerformed

    private void botaoadicionarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoadicionarMouseEntered
        getBotaoadicionar().setBackground(new Color(204, 204, 204)); // cor de fundo quando aparece
        getBotaoadicionar().setForeground(new Color(255, 255, 255)); // cor da letra quando aparece
    }//GEN-LAST:event_botaoadicionarMouseEntered

    private void botaoadicionarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoadicionarMouseExited
        getBotaoadicionar().setBackground(new Color(255, 255, 255));// Fundo Quando Solta
        getBotaoadicionar().setForeground(new Color(0, 102, 102));// letra quando solta cor
    }//GEN-LAST:event_botaoadicionarMouseExited

    private void botaoadicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoadicionarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoadicionarActionPerformed

    private void botaoFecharMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoFecharMouseEntered
        getBotaoFechar().setBackground(new Color(204, 204, 204)); // cor de fundo quando aparece
        getBotaoFechar().setForeground(new Color(255, 255, 255)); // cor da letra quando aparece
    }//GEN-LAST:event_botaoFecharMouseEntered

    private void botaoFecharMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoFecharMouseExited
        getBotaoFechar().setBackground(new Color(255, 255, 255));// Fundo Quando Solta
        getBotaoFechar().setForeground(new Color(0, 102, 102));// letra quando solta cor
    }//GEN-LAST:event_botaoFecharMouseExited

    private void botaoFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoFecharActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoFecharActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoCancelar;
    private javax.swing.JButton botaoFechar;
    private javax.swing.JButton botaoSalvarconta;
    private javax.swing.JButton botaoadicionar;
    private javax.swing.JComboBox<String> combopagamento;
    private javax.swing.JComboBox<String> combotipo;
    private com.toedter.calendar.JDateChooser dataemissaoconta;
    private com.toedter.calendar.JDateChooser datavencimentoconta;
    private javax.swing.JTextField descricaoConta;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    private java.awt.Label label14;
    private java.awt.Label label15;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.Label label6;
    private javax.swing.JLabel labelcadastro2;
    private javax.swing.JPanel panelContas;
    private javax.swing.JTable tabelaconta;
    private javax.swing.JTextField txtPesquisa;
    private javax.swing.JTextField valorconta;
    // End of variables declaration//GEN-END:variables

  
    public void Limpar() {

        getDescricaoConta().setText("");
        getDataemissaoconta().setDate(null);
        getDatavencimentoconta().setDate(null);
        getValorconta().setText("");
        getCombopagamento().setSelectedIndex(0);
        getCombotipo().setSelectedIndex(0);

    }

    public void preencherCadastro(ContaaPagar p) {

        getDescricaoConta().setText(p.getDescricao());
        getDataemissaoconta().setDate(p.getData_emissao());
        getDatavencimentoconta().setDate(p.getData_vencimento());
        getValorconta().setText(p.getValor() + "");

        for (int u = 0; u < getCombopagamento().getItemCount(); u++) {

            if (getCombopagamento().getItemAt(u).equals(p.getForma_pagamento())) {
                getCombopagamento().setSelectedItem(getCombopagamento().getItemAt(u));
            }
        }

        for (int u = 0; u < getCombotipo().getItemCount(); u++) {

            if (getCombotipo().getItemAt(u).equals(p.getTipo())) {
                getCombotipo().setSelectedItem(getCombotipo().getItemAt(u));

            }
        }

    }

    /**
     * @return the Iconeditar
     */
    public Icon getIconeditar() {
        return Iconeditar;
    }

    /**
     * @param Iconeditar the Iconeditar to set
     */
    public void setIconeditar(Icon Iconeditar) {
        this.Iconeditar = Iconeditar;
    }

    /**
     * @return the Iconexcluir
     */
    public Icon getIconexcluir() {
        return Iconexcluir;
    }

    /**
     * @param Iconexcluir the Iconexcluir to set
     */
    public void setIconexcluir(Icon Iconexcluir) {
        this.Iconexcluir = Iconexcluir;
    }

    /**
     * @return the btnEx
     */
    public JButton getBtnEx() {
        return btnEx;
    }

    /**
     * @param btnEx the btnEx to set
     */
    public void setBtnEx(JButton btnEx) {
        this.btnEx = btnEx;
    }

    /**
     * @return the btnEd
     */
    public JButton getBtnEd() {
        return btnEd;
    }

    /**
     * @param btnEd the btnEd to set
     */
    public void setBtnEd(JButton btnEd) {
        this.btnEd = btnEd;
    }

    /**
     * @return the btnPag
     */
    public JButton getBtnPag() {
        return btnPag;
    }

    /**
     * @param btnPag the btnPag to set
     */
    public void setBtnPag(JButton btnPag) {
        this.btnPag = btnPag;
    }

    /**
     * @return the Iconpagar
     */
    public Icon getIconpagar() {
        return Iconpagar;
    }

    /**
     * @param Iconpagar the Iconpagar to set
     */
    public void setIconpagar(Icon Iconpagar) {
        this.Iconpagar = Iconpagar;
    }

    /**
     * @return the botaoCancelar
     */
    public javax.swing.JButton getBotaoCancelar() {
        return botaoCancelar;
    }

    /**
     * @param botaoCancelar the botaoCancelar to set
     */
    public void setBotaoCancelar(javax.swing.JButton botaoCancelar) {
        this.botaoCancelar = botaoCancelar;
    }

    /**
     * @return the botaoFechar
     */
    public javax.swing.JButton getBotaoFechar() {
        return botaoFechar;
    }

    /**
     * @param botaoFechar the botaoFechar to set
     */
    public void setBotaoFechar(javax.swing.JButton botaoFechar) {
        this.botaoFechar = botaoFechar;
    }

    /**
     * @return the botaoSalvarconta
     */
    public javax.swing.JButton getBotaoSalvarconta() {
        return botaoSalvarconta;
    }

    /**
     * @param botaoSalvarconta the botaoSalvarconta to set
     */
    public void setBotaoSalvarconta(javax.swing.JButton botaoSalvarconta) {
        this.botaoSalvarconta = botaoSalvarconta;
    }

    /**
     * @return the botaoadicionar
     */
    public javax.swing.JButton getBotaoadicionar() {
        return botaoadicionar;
    }

    /**
     * @param botaoadicionar the botaoadicionar to set
     */
    public void setBotaoadicionar(javax.swing.JButton botaoadicionar) {
        this.botaoadicionar = botaoadicionar;
    }

    /**
     * @return the combopagamento
     */
    public javax.swing.JComboBox<String> getCombopagamento() {
        return combopagamento;
    }

    /**
     * @param combopagamento the combopagamento to set
     */
    public void setCombopagamento(javax.swing.JComboBox<String> combopagamento) {
        this.combopagamento = combopagamento;
    }

    /**
     * @return the combotipo
     */
    public javax.swing.JComboBox<String> getCombotipo() {
        return combotipo;
    }

    /**
     * @param combotipo the combotipo to set
     */
    public void setCombotipo(javax.swing.JComboBox<String> combotipo) {
        this.combotipo = combotipo;
    }

    /**
     * @return the dataemissaoconta
     */
    public com.toedter.calendar.JDateChooser getDataemissaoconta() {
        return dataemissaoconta;
    }

    /**
     * @param dataemissaoconta the dataemissaoconta to set
     */
    public void setDataemissaoconta(com.toedter.calendar.JDateChooser dataemissaoconta) {
        this.dataemissaoconta = dataemissaoconta;
    }

    /**
     * @return the datavencimentoconta
     */
    public com.toedter.calendar.JDateChooser getDatavencimentoconta() {
        return datavencimentoconta;
    }

    /**
     * @param datavencimentoconta the datavencimentoconta to set
     */
    public void setDatavencimentoconta(com.toedter.calendar.JDateChooser datavencimentoconta) {
        this.datavencimentoconta = datavencimentoconta;
    }

    /**
     * @return the descricaoConta
     */
    public javax.swing.JTextField getDescricaoConta() {
        return descricaoConta;
    }

    /**
     * @param descricaoConta the descricaoConta to set
     */
    public void setDescricaoConta(javax.swing.JTextField descricaoConta) {
        this.descricaoConta = descricaoConta;
    }

    /**
     * @return the jLabel2
     */
    public javax.swing.JLabel getjLabel2() {
        return jLabel2;
    }

    /**
     * @param jLabel2 the jLabel2 to set
     */
    public void setjLabel2(javax.swing.JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }

    /**
     * @return the jPanel1
     */
    public javax.swing.JPanel getjPanel1() {
        return jPanel1;
    }

    /**
     * @param jPanel1 the jPanel1 to set
     */
    public void setjPanel1(javax.swing.JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    /**
     * @return the jPanel3
     */
    public javax.swing.JPanel getjPanel3() {
        return jPanel3;
    }

    /**
     * @param jPanel3 the jPanel3 to set
     */
    public void setjPanel3(javax.swing.JPanel jPanel3) {
        this.jPanel3 = jPanel3;
    }

    /**
     * @return the jPanel9
     */
    public javax.swing.JPanel getjPanel9() {
        return jPanel9;
    }

    /**
     * @param jPanel9 the jPanel9 to set
     */
    public void setjPanel9(javax.swing.JPanel jPanel9) {
        this.jPanel9 = jPanel9;
    }

    /**
     * @return the jScrollPane2
     */
    public javax.swing.JScrollPane getjScrollPane2() {
        return jScrollPane2;
    }

    /**
     * @param jScrollPane2 the jScrollPane2 to set
     */
    public void setjScrollPane2(javax.swing.JScrollPane jScrollPane2) {
        this.jScrollPane2 = jScrollPane2;
    }

    /**
     * @return the label14
     */
    public java.awt.Label getLabel14() {
        return label14;
    }

    /**
     * @param label14 the label14 to set
     */
    public void setLabel14(java.awt.Label label14) {
        this.label14 = label14;
    }

    /**
     * @return the label15
     */
    public java.awt.Label getLabel15() {
        return label15;
    }

    /**
     * @param label15 the label15 to set
     */
    public void setLabel15(java.awt.Label label15) {
        this.label15 = label15;
    }

    /**
     * @return the label2
     */
    public java.awt.Label getLabel2() {
        return label2;
    }

    /**
     * @param label2 the label2 to set
     */
    public void setLabel2(java.awt.Label label2) {
        this.label2 = label2;
    }

    /**
     * @return the label3
     */
    public java.awt.Label getLabel3() {
        return label3;
    }

    /**
     * @param label3 the label3 to set
     */
    public void setLabel3(java.awt.Label label3) {
        this.label3 = label3;
    }

    /**
     * @return the label4
     */
    public java.awt.Label getLabel4() {
        return label4;
    }

    /**
     * @param label4 the label4 to set
     */
    public void setLabel4(java.awt.Label label4) {
        this.label4 = label4;
    }

    /**
     * @return the label5
     */
    public java.awt.Label getLabel5() {
        return label5;
    }

    /**
     * @param label5 the label5 to set
     */
    public void setLabel5(java.awt.Label label5) {
        this.label5 = label5;
    }

    /**
     * @return the label6
     */
    public java.awt.Label getLabel6() {
        return label6;
    }

    /**
     * @param label6 the label6 to set
     */
    public void setLabel6(java.awt.Label label6) {
        this.label6 = label6;
    }

    /**
     * @return the labelcadastro2
     */
    public javax.swing.JLabel getLabelcadastro2() {
        return labelcadastro2;
    }

    /**
     * @param labelcadastro2 the labelcadastro2 to set
     */
    public void setLabelcadastro2(javax.swing.JLabel labelcadastro2) {
        this.labelcadastro2 = labelcadastro2;
    }

    /**
     * @return the panelContas
     */
    public javax.swing.JPanel getPanelContas() {
        return panelContas;
    }

    /**
     * @param panelContas the panelContas to set
     */
    public void setPanelContas(javax.swing.JPanel panelContas) {
        this.panelContas = panelContas;
    }

    /**
     * @return the tabelaconta
     */
    public javax.swing.JTable getTabelaconta() {
        return tabelaconta;
    }

    /**
     * @param tabelaconta the tabelaconta to set
     */
    public void setTabelaconta(javax.swing.JTable tabelaconta) {
        this.tabelaconta = tabelaconta;
    }

    /**
     * @return the txtPesquisa
     */
    public javax.swing.JTextField getTxtPesquisa() {
        return txtPesquisa;
    }

    /**
     * @param txtPesquisa the txtPesquisa to set
     */
    public void setTxtPesquisa(javax.swing.JTextField txtPesquisa) {
        this.txtPesquisa = txtPesquisa;
    }

    /**
     * @return the valorconta
     */
    public javax.swing.JTextField getValorconta() {
        return valorconta;
    }

    /**
     * @param valorconta the valorconta to set
     */
    public void setValorconta(javax.swing.JTextField valorconta) {
        this.valorconta = valorconta;
    }
   

}
