/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.pbd.view;

import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.util.HashMap;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JInternalFrame;
import javax.swing.JLabel;

/**
 *
 * @author Glenda Alves de Lima
 */
public class Mensagens extends javax.swing.JDialog implements KeyListener {

    private HashMap<Integer, Boolean> keyEventos;

    /**
     * Creates new form Mensagems
     */
    private final String CADASTRO, EDICAO, ERRO, DADOSVAZIO,RESET;
    private final Icon imgADV, imgINF, imgERRO;

    public Mensagens(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.CADASTRO = "Cadastro Realizado";
        this.EDICAO = "Ediçao Realizada";
        this.ERRO = "Erro";
        this.DADOSVAZIO = "Preencha todos os campos";
        this.RESET= "Reset Realizado";
        imgADV = new ImageIcon(getClass().getResource("/br/com/pbd/resource/advertencia.png"));
        imgINF = new ImageIcon(getClass().getResource("/br/com/pbd/resource/info.png"));
        imgERRO = new ImageIcon(getClass().getResource("/br/com/pbd/resource/erro.png"));

        keyEventos = new HashMap<Integer, Boolean>();
        BotaoOk.addKeyListener(this);
        this.addKeyListener(this);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Icone = new javax.swing.JLabel();
        mensagem = new java.awt.Label();
        BotaoOk = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(226, 226, 226));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        Icone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/pbd/resource/advertencia.png"))); // NOI18N

        mensagem.setName(""); // NOI18N

        BotaoOk.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BotaoOk.setText("OK");
        BotaoOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoOkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Icone)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mensagem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(155, Short.MAX_VALUE)
                .addComponent(BotaoOk, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(135, 135, 135))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Icone)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(mensagem, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)))
                .addComponent(BotaoOk)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setBounds(650, 220, 358, 129);
    }// </editor-fold>//GEN-END:initComponents

    private void BotaoOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoOkActionPerformed
        setVisible(false);
    }//GEN-LAST:event_BotaoOkActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mensagens.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mensagens.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mensagens.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mensagens.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Mensagens dialog = new Mensagens(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoOk;
    private javax.swing.JLabel Icone;
    private javax.swing.JPanel jPanel1;
    private java.awt.Label mensagem;
    // End of variables declaration//GEN-END:variables

    public void mensagens(String mensagen, String icon) {
        Icon img1 = new ImageIcon(getClass().getResource("/br/com/pbd/resource/" + icon + ".png"));
        Icone.setIcon(img1);
        mensagem.setText(mensagen);
        setVisible(true);
    }

    public void mnsERRO() {
        Icone.setIcon(imgERRO);
        mensagem.setText(ERRO);
        setVisible(true);
    }

    public void mnscadastro() {
        Icone.setIcon(imgINF);
        mensagem.setText(CADASTRO);
        setVisible(true);
    }

    public void mnsEdicao() {
        Icone.setIcon(imgINF);
        mensagem.setText(EDICAO);
        setVisible(true);
    }

    public void mnsADV() {
        Icone.setIcon(imgADV);
        mensagem.setText(DADOSVAZIO);
        setVisible(true);
    }

    public void mnsReset() {
        Icone.setIcon(imgINF);
        mensagem.setText(RESET);
        setVisible(true);
    }

    /**
     * @return the BotaoOk
     */
    public javax.swing.JButton getBotaoOk() {
        return BotaoOk;
    }

    /**
     * @return the Icone
     */
    public javax.swing.JLabel getIcone() {
        return Icone;
    }

    /**
     * @return the mensagem
     */
    public java.awt.Label getMensagem() {
        return mensagem;
    }

    @Override
    public void keyPressed(KeyEvent e) {
        keyEventos.put(e.getKeyCode(), true);

        if (e.getKeyCode() == KeyEvent.VK_ENTER) {
            setVisible(false);
        }

    }

    @Override
    public void keyReleased(KeyEvent e) {
        keyEventos.remove(e.getKeyCode());
    }

    @Override
    public void keyTyped(KeyEvent e) {
    }

}
