/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.pbd.view;

import java.awt.Color;
import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.JDialog;
import javax.swing.JInternalFrame;
import javax.swing.JTextField;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author Glenda Alves de Lima
 */
public class Principal extends javax.swing.JFrame implements ActionListener {
    
    private CadastroAlunos cadastroAlunos = new CadastroAlunos();
    private BuscarAlunos buscarAlunos = new BuscarAlunos();
    private BuscarProfessor buscarProfessor = new BuscarProfessor();
    private CadastroProfessor cadastroProfessor = new CadastroProfessor();
    private FundoPrincipal fundoPrincipal = new FundoPrincipal();
    private TelaAcompanhamento acompanhamento = new TelaAcompanhamento();
    private ListaAcompanhamento listaAcompanhamento = new ListaAcompanhamento();
    private TelaExercicio exercicio = new TelaExercicio();
    private TelaAcademia academia = new TelaAcademia();
    private TelaTarefa tarefa = new TelaTarefa();
    private CadastroFornecedor cadastroFornecedor = new CadastroFornecedor();
    private BuscarFornecedor buscarFornecedor = new BuscarFornecedor();
    private TelaProduto produto = new TelaProduto();
    private CadastroFuncionario cadastroFuncionario = new CadastroFuncionario();
    private BuscarFuncionario buscarFuncionario = new BuscarFuncionario();
    private Caixa caixa = new Caixa();
    private Mensalidade mensalidade = new Mensalidade();
    private AgendaSemana agendaAluno = new AgendaSemana();
    private AgendaSemana agendaprofessor = new AgendaSemana();
    private AgendaExercicios agendaExercicios = new AgendaExercicios();
    private ListaExercicio listaExercicio = new ListaExercicio();
    private ListaMensalidades listaMensalidades = new ListaMensalidades();
    private Despesas despesas = new Despesas();
    private Venda venda = new Venda();
    private TelaSobre telaSobre = new TelaSobre();
    private ExerciciosTreino exerciciosTreino = new ExerciciosTreino();
    private Gerencia gerencia = new Gerencia();
    private Relatorios relatorios = new Relatorios();
    
    public Principal() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        
        fundos(cadastroAlunos);
        fundos(buscarAlunos);
        fundos(cadastroProfessor);
        fundos(buscarProfessor);
        fundos(fundoPrincipal);
        fundos(acompanhamento);
        fundos(exercicio);
        fundos(academia);
        fundos(tarefa);
        fundos(cadastroFornecedor);
        fundos(buscarFornecedor);
        fundos(produto);
        fundos(buscarFuncionario);
        fundos(cadastroFuncionario);
        fundos(caixa);
        fundos(mensalidade);
        fundos(listaAcompanhamento);
        fundos(agendaAluno);
        fundos(agendaprofessor);
        fundos(agendaExercicios);
        fundos(listaExercicio);
        fundos(listaMensalidades);
        fundos(despesas);
        fundos(venda);
        fundos(telaSobre);
        fundos(exerciciosTreino);
        fundos(gerencia);
        fundos(relatorios);
        
        fundoPrincipal.setVisible(rootPaneCheckingEnabled);
        
        buscarFuncionario.getBotaoAdicionar().addActionListener(this);
        buscarAlunos.getBotaoAdicionar().addActionListener(this);
        buscarProfessor.getBotaoAdicionar().addActionListener(this);
        buscarFornecedor.getBotaoAdicionar().addActionListener(this);
        listaAcompanhamento.getBotaoAdicionar().addActionListener(this);
        getBuscarFuncionario().getBotaoAdicionar().addActionListener(this);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        areaPanel = new javax.swing.JDesktopPane();
        painelMenuPrincipal = new javax.swing.JPanel();
        botaoFornecedor = new javax.swing.JButton();
        botaoAluno = new javax.swing.JButton();
        botaoTarefa = new javax.swing.JButton();
        botaoFuncionario = new javax.swing.JButton();
        botaoProduto = new javax.swing.JButton();
        botaoExercicio = new javax.swing.JButton();
        botaoDespesas = new javax.swing.JButton();
        botaoCaixa = new javax.swing.JButton();
        botaoRelatorios = new javax.swing.JButton();
        botaoVenda = new javax.swing.JButton();
        botaoAcademia = new javax.swing.JButton();
        botaologoff = new javax.swing.JButton();
        botaoProfessor = new javax.swing.JButton();
        botaoAgenda = new javax.swing.JButton();
        botaoSair = new javax.swing.JButton();
        botaoAcesso = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        labelnome = new java.awt.Label();
        labelfuncao = new java.awt.Label();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        areaPanel.setPreferredSize(new java.awt.Dimension(962, 739));

        javax.swing.GroupLayout areaPanelLayout = new javax.swing.GroupLayout(areaPanel);
        areaPanel.setLayout(areaPanelLayout);
        areaPanelLayout.setHorizontalGroup(
            areaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 962, Short.MAX_VALUE)
        );
        areaPanelLayout.setVerticalGroup(
            areaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        painelMenuPrincipal.setBackground(new java.awt.Color(255, 255, 255));

        botaoFornecedor.setBackground(new java.awt.Color(255, 255, 255));
        botaoFornecedor.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        botaoFornecedor.setForeground(new java.awt.Color(0, 102, 102));
        botaoFornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/pbd/resource/user (1).png"))); // NOI18N
        botaoFornecedor.setText("Fornecedor");
        botaoFornecedor.setBorderPainted(false);
        botaoFornecedor.setFocusPainted(false);
        botaoFornecedor.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        botaoFornecedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botaoFornecedorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botaoFornecedorMouseExited(evt);
            }
        });
        botaoFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoFornecedorActionPerformed(evt);
            }
        });

        botaoAluno.setBackground(new java.awt.Color(255, 255, 255));
        botaoAluno.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        botaoAluno.setForeground(new java.awt.Color(0, 102, 102));
        botaoAluno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/pbd/resource/followers (1).png"))); // NOI18N
        botaoAluno.setText("Aluno");
        botaoAluno.setBorderPainted(false);
        botaoAluno.setFocusPainted(false);
        botaoAluno.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        botaoAluno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botaoAlunoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botaoAlunoMouseExited(evt);
            }
        });
        botaoAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAlunoActionPerformed(evt);
            }
        });

        botaoTarefa.setBackground(new java.awt.Color(255, 255, 255));
        botaoTarefa.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        botaoTarefa.setForeground(new java.awt.Color(0, 102, 102));
        botaoTarefa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/pbd/resource/task-planning.png"))); // NOI18N
        botaoTarefa.setText("Tarefa");
        botaoTarefa.setBorderPainted(false);
        botaoTarefa.setFocusPainted(false);
        botaoTarefa.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        botaoTarefa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botaoTarefaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botaoTarefaMouseExited(evt);
            }
        });
        botaoTarefa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoTarefaActionPerformed(evt);
            }
        });

        botaoFuncionario.setBackground(new java.awt.Color(255, 255, 255));
        botaoFuncionario.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        botaoFuncionario.setForeground(new java.awt.Color(0, 102, 102));
        botaoFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/pbd/resource/management.png"))); // NOI18N
        botaoFuncionario.setText("Funcionario");
        botaoFuncionario.setBorderPainted(false);
        botaoFuncionario.setFocusPainted(false);
        botaoFuncionario.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        botaoFuncionario.setPreferredSize(new java.awt.Dimension(159, 54));
        botaoFuncionario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botaoFuncionarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botaoFuncionarioMouseExited(evt);
            }
        });
        botaoFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoFuncionarioActionPerformed(evt);
            }
        });

        botaoProduto.setBackground(new java.awt.Color(255, 255, 255));
        botaoProduto.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        botaoProduto.setForeground(new java.awt.Color(0, 102, 102));
        botaoProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/pbd/resource/sugar-cube (1).png"))); // NOI18N
        botaoProduto.setText("Produto");
        botaoProduto.setBorderPainted(false);
        botaoProduto.setFocusPainted(false);
        botaoProduto.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        botaoProduto.setPreferredSize(new java.awt.Dimension(159, 54));
        botaoProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botaoProdutoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botaoProdutoMouseExited(evt);
            }
        });
        botaoProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoProdutoActionPerformed(evt);
            }
        });

        botaoExercicio.setBackground(new java.awt.Color(255, 255, 255));
        botaoExercicio.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        botaoExercicio.setForeground(new java.awt.Color(0, 102, 102));
        botaoExercicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/pbd/resource/gym.png"))); // NOI18N
        botaoExercicio.setText("Exercicio");
        botaoExercicio.setBorderPainted(false);
        botaoExercicio.setFocusPainted(false);
        botaoExercicio.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        botaoExercicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botaoExercicioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botaoExercicioMouseExited(evt);
            }
        });
        botaoExercicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoExercicioActionPerformed(evt);
            }
        });

        botaoDespesas.setBackground(new java.awt.Color(255, 255, 255));
        botaoDespesas.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        botaoDespesas.setForeground(new java.awt.Color(0, 102, 102));
        botaoDespesas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/pbd/resource/protection.png"))); // NOI18N
        botaoDespesas.setText("Despesas");
        botaoDespesas.setBorderPainted(false);
        botaoDespesas.setFocusPainted(false);
        botaoDespesas.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        botaoDespesas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botaoDespesasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botaoDespesasMouseExited(evt);
            }
        });
        botaoDespesas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoDespesasActionPerformed(evt);
            }
        });

        botaoCaixa.setBackground(new java.awt.Color(255, 255, 255));
        botaoCaixa.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        botaoCaixa.setForeground(new java.awt.Color(0, 102, 102));
        botaoCaixa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/pbd/resource/ticket.png"))); // NOI18N
        botaoCaixa.setText("Caixa     ");
        botaoCaixa.setBorderPainted(false);
        botaoCaixa.setFocusPainted(false);
        botaoCaixa.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        botaoCaixa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botaoCaixaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botaoCaixaMouseExited(evt);
            }
        });
        botaoCaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCaixaActionPerformed(evt);
            }
        });

        botaoRelatorios.setBackground(new java.awt.Color(255, 255, 255));
        botaoRelatorios.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        botaoRelatorios.setForeground(new java.awt.Color(0, 102, 102));
        botaoRelatorios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/pbd/resource/send-file.png"))); // NOI18N
        botaoRelatorios.setText("Relatorio");
        botaoRelatorios.setBorderPainted(false);
        botaoRelatorios.setFocusPainted(false);
        botaoRelatorios.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        botaoRelatorios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botaoRelatoriosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botaoRelatoriosMouseExited(evt);
            }
        });
        botaoRelatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoRelatoriosActionPerformed(evt);
            }
        });

        botaoVenda.setBackground(new java.awt.Color(255, 255, 255));
        botaoVenda.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        botaoVenda.setForeground(new java.awt.Color(0, 102, 102));
        botaoVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/pbd/resource/shopping-cart.png"))); // NOI18N
        botaoVenda.setText("Venda");
        botaoVenda.setBorderPainted(false);
        botaoVenda.setFocusPainted(false);
        botaoVenda.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        botaoVenda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botaoVendaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botaoVendaMouseExited(evt);
            }
        });
        botaoVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVendaActionPerformed(evt);
            }
        });

        botaoAcademia.setBackground(new java.awt.Color(255, 255, 255));
        botaoAcademia.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        botaoAcademia.setForeground(new java.awt.Color(0, 102, 102));
        botaoAcademia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/pbd/resource/buildings.png"))); // NOI18N
        botaoAcademia.setText("Academia");
        botaoAcademia.setBorderPainted(false);
        botaoAcademia.setFocusPainted(false);
        botaoAcademia.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        botaoAcademia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botaoAcademiaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botaoAcademiaMouseExited(evt);
            }
        });
        botaoAcademia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAcademiaActionPerformed(evt);
            }
        });

        botaologoff.setBackground(new java.awt.Color(255, 255, 255));
        botaologoff.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        botaologoff.setForeground(new java.awt.Color(0, 102, 102));
        botaologoff.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/pbd/resource/Logoff.png"))); // NOI18N
        botaologoff.setText("Logoff");
        botaologoff.setToolTipText("");
        botaologoff.setBorderPainted(false);
        botaologoff.setFocusPainted(false);
        botaologoff.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        botaologoff.setPreferredSize(new java.awt.Dimension(144, 72));
        botaologoff.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botaologoffMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botaologoffMouseExited(evt);
            }
        });

        botaoProfessor.setBackground(new java.awt.Color(255, 255, 255));
        botaoProfessor.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        botaoProfessor.setForeground(new java.awt.Color(0, 102, 102));
        botaoProfessor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/pbd/resource/add-user.png"))); // NOI18N
        botaoProfessor.setText("Professores");
        botaoProfessor.setBorderPainted(false);
        botaoProfessor.setFocusPainted(false);
        botaoProfessor.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        botaoProfessor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botaoProfessorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botaoProfessorMouseExited(evt);
            }
        });
        botaoProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoProfessorActionPerformed(evt);
            }
        });

        botaoAgenda.setBackground(new java.awt.Color(255, 255, 255));
        botaoAgenda.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        botaoAgenda.setForeground(new java.awt.Color(0, 102, 102));
        botaoAgenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/pbd/resource/calendar (2).png"))); // NOI18N
        botaoAgenda.setText("Agenda");
        botaoAgenda.setBorderPainted(false);
        botaoAgenda.setFocusPainted(false);
        botaoAgenda.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        botaoAgenda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botaoAgendaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botaoAgendaMouseExited(evt);
            }
        });
        botaoAgenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAgendaActionPerformed(evt);
            }
        });

        botaoSair.setBackground(new java.awt.Color(255, 255, 255));
        botaoSair.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        botaoSair.setForeground(new java.awt.Color(0, 102, 102));
        botaoSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/pbd/resource/Sair.png"))); // NOI18N
        botaoSair.setText("Sair        ");
        botaoSair.setToolTipText("");
        botaoSair.setBorderPainted(false);
        botaoSair.setFocusPainted(false);
        botaoSair.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        botaoSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botaoSairMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botaoSairMouseExited(evt);
            }
        });
        botaoSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSairActionPerformed(evt);
            }
        });

        botaoAcesso.setBackground(new java.awt.Color(255, 255, 255));
        botaoAcesso.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        botaoAcesso.setForeground(new java.awt.Color(0, 102, 102));
        botaoAcesso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/pbd/resource/vision.png"))); // NOI18N
        botaoAcesso.setText("Acesso");
        botaoAcesso.setBorderPainted(false);
        botaoAcesso.setFocusPainted(false);
        botaoAcesso.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        botaoAcesso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botaoAcessoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botaoAcessoMouseExited(evt);
            }
        });
        botaoAcesso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAcessoActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/pbd/resource/Use.png"))); // NOI18N

        labelnome.setFont(new java.awt.Font("DeVinne Txt BT", 1, 18)); // NOI18N
        labelnome.setForeground(new java.awt.Color(0, 102, 102));
        labelnome.setText("Nome");

        labelfuncao.setFont(new java.awt.Font("DeVinne Txt BT", 1, 18)); // NOI18N
        labelfuncao.setForeground(new java.awt.Color(0, 102, 102));
        labelfuncao.setText("Função");

        javax.swing.GroupLayout painelMenuPrincipalLayout = new javax.swing.GroupLayout(painelMenuPrincipal);
        painelMenuPrincipal.setLayout(painelMenuPrincipalLayout);
        painelMenuPrincipalLayout.setHorizontalGroup(
            painelMenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelMenuPrincipalLayout.createSequentialGroup()
                .addGroup(painelMenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botaoProduto, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                    .addComponent(botaoTarefa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botaoAluno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0)
                .addGroup(painelMenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(botaoFornecedor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botaoProfessor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botaoFuncionario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(painelMenuPrincipalLayout.createSequentialGroup()
                .addGroup(painelMenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botaoRelatorios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(painelMenuPrincipalLayout.createSequentialGroup()
                        .addComponent(botaoCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(botaologoff, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botaoExercicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botaoAcesso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(painelMenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(botaoAcademia, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                    .addComponent(botaoDespesas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botaoAgenda, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botaoSair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botaoVenda, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(painelMenuPrincipalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelMenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelnome, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                    .addComponent(labelfuncao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(62, 62, 62))
        );
        painelMenuPrincipalLayout.setVerticalGroup(
            painelMenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelMenuPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelMenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(painelMenuPrincipalLayout.createSequentialGroup()
                        .addComponent(labelnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(labelfuncao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(painelMenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botaoProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoAluno, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelMenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botaoFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoTarefa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelMenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(painelMenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoExercicio, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoAgenda, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelMenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelMenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoRelatorios, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoDespesas, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelMenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoAcesso, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoAcademia, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelMenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaologoff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoSair))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelMenuPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(areaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(painelMenuPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(areaPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoFornecedorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoFornecedorMouseEntered
        getBotaoFornecedor().setBackground(new Color(204, 204, 204)); // cor de fundo quando aparece
        getBotaoFornecedor().setForeground(new Color(255, 255, 255)); // cor da letra quando aparece
    }//GEN-LAST:event_botaoFornecedorMouseEntered

    private void botaoFornecedorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoFornecedorMouseExited
        getBotaoFornecedor().setBackground(new Color(255, 255, 255));// Fundo Quando Solta
        getBotaoFornecedor().setForeground(new Color(0, 102, 102));// letra quando solta cor
    }//GEN-LAST:event_botaoFornecedorMouseExited

    private void botaoFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoFornecedorActionPerformed
        Apenasnumero(getCadastroFornecedor().getTxtnumero());
        getBuscarFornecedor().setVisible(true);
    }//GEN-LAST:event_botaoFornecedorActionPerformed

    private void botaoAlunoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoAlunoMouseEntered
        getBotaoAluno().setBackground(new Color(204, 204, 204)); // cor de fundo quando aparece
        getBotaoAluno().setForeground(new Color(255, 255, 255)); // cor da letra quando aparece
    }//GEN-LAST:event_botaoAlunoMouseEntered

    private void botaoAlunoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoAlunoMouseExited
        getBotaoAluno().setBackground(new Color(255, 255, 255));// Fundo Quando Solta
        getBotaoAluno().setForeground(new Color(0, 102, 102));// letra quando solta cor
    }//GEN-LAST:event_botaoAlunoMouseExited

    private void botaoAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAlunoActionPerformed
        Apenasnumero(getCadastroAlunos().getTxtnumero());
        getBuscarAlunos().setVisible(true);
    }//GEN-LAST:event_botaoAlunoActionPerformed

    private void botaoTarefaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoTarefaMouseEntered
        getBotaoTarefa().setBackground(new Color(204, 204, 204)); // cor de fundo quando aparece
        getBotaoTarefa().setForeground(new Color(255, 255, 255)); // cor da letra quando aparece
    }//GEN-LAST:event_botaoTarefaMouseEntered

    private void botaoTarefaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoTarefaMouseExited
        getBotaoTarefa().setBackground(new Color(255, 255, 255));// Fundo Quando Solta
        getBotaoTarefa().setForeground(new Color(0, 102, 102));// letra quando solta cor
    }//GEN-LAST:event_botaoTarefaMouseExited

    private void botaoTarefaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoTarefaActionPerformed
        getTarefa().setVisible(true);
    }//GEN-LAST:event_botaoTarefaActionPerformed

    private void botaoFuncionarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoFuncionarioMouseEntered
        getBotaoFuncionario().setBackground(new Color(204, 204, 204)); // cor de fundo quando aparece
        getBotaoFuncionario().setForeground(new Color(255, 255, 255)); // cor da letra quando aparece
    }//GEN-LAST:event_botaoFuncionarioMouseEntered

    private void botaoFuncionarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoFuncionarioMouseExited
        getBotaoFuncionario().setBackground(new Color(255, 255, 255));// Fundo Quando Solta
        getBotaoFuncionario().setForeground(new Color(0, 102, 102));// letra quando solta cor
    }//GEN-LAST:event_botaoFuncionarioMouseExited

    private void botaoFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoFuncionarioActionPerformed
        Apenasnumero(getCadastroFuncionario().getTxtnumero());
        getBuscarFuncionario().setVisible(true);
    }//GEN-LAST:event_botaoFuncionarioActionPerformed

    private void botaoProdutoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoProdutoMouseEntered
        getBotaoProduto().setBackground(new Color(204, 204, 204)); // cor de fundo quando aparece
        getBotaoProduto().setForeground(new Color(255, 255, 255)); // cor da letra quando aparece
    }//GEN-LAST:event_botaoProdutoMouseEntered

    private void botaoProdutoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoProdutoMouseExited
        getBotaoProduto().setBackground(new Color(255, 255, 255));// Fundo Quando Solta
        getBotaoProduto().setForeground(new Color(0, 102, 102));// letra quando solta cor
    }//GEN-LAST:event_botaoProdutoMouseExited

    private void botaoProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoProdutoActionPerformed
        Apenasnumero(getProduto().getTxtestoqueatual());
        ApenasnumeroP(getProduto().getTxtvenda());
    }//GEN-LAST:event_botaoProdutoActionPerformed

    private void botaoExercicioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoExercicioMouseEntered
        getBotaoExercicio().setBackground(new Color(204, 204, 204)); // cor de fundo quando aparece
        getBotaoExercicio().setForeground(new Color(255, 255, 255)); // cor da letra quando aparece
    }//GEN-LAST:event_botaoExercicioMouseEntered

    private void botaoExercicioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoExercicioMouseExited
        getBotaoExercicio().setBackground(new Color(255, 255, 255));// Fundo Quando Solta
        getBotaoExercicio().setForeground(new Color(0, 102, 102));// letra quando solta cor
    }//GEN-LAST:event_botaoExercicioMouseExited

    private void botaoExercicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoExercicioActionPerformed
        Apenasnumero(getExercicio().getTxtrepeticao());
        Apenasnumero(getExercicio().getTxtserie());
        ApenasnumeroP(getExercicio().getTxtpeso());
        getExercicio().setVisible(true);
    }//GEN-LAST:event_botaoExercicioActionPerformed

    private void botaoDespesasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoDespesasMouseEntered
        getBotaoDespesas().setBackground(new Color(204, 204, 204)); // cor de fundo quando aparece
        getBotaoDespesas().setForeground(new Color(255, 255, 255)); // cor da letra quando aparece
    }//GEN-LAST:event_botaoDespesasMouseEntered

    private void botaoDespesasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoDespesasMouseExited
        getBotaoDespesas().setBackground(new Color(255, 255, 255));// Fundo Quando Solta
        getBotaoDespesas().setForeground(new Color(0, 102, 102));// letra quando solta cor
    }//GEN-LAST:event_botaoDespesasMouseExited

    private void botaoCaixaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoCaixaMouseEntered
        getBotaoCaixa().setBackground(new Color(204, 204, 204)); // cor de fundo quando aparece
        getBotaoCaixa().setForeground(new Color(255, 255, 255)); // cor da letra quando aparece
    }//GEN-LAST:event_botaoCaixaMouseEntered

    private void botaoCaixaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoCaixaMouseExited
        getBotaoCaixa().setBackground(new Color(255, 255, 255));// Fundo Quando Solta
        getBotaoCaixa().setForeground(new Color(0, 102, 102));// letra quando solta cor
    }//GEN-LAST:event_botaoCaixaMouseExited

    private void botaoCaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCaixaActionPerformed
        getCaixa().setVisible(true);
    }//GEN-LAST:event_botaoCaixaActionPerformed

    private void botaoRelatoriosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoRelatoriosMouseEntered
        getBotaoRelatorios().setBackground(new Color(204, 204, 204)); // cor de fundo quando aparece
        getBotaoRelatorios().setForeground(new Color(255, 255, 255)); // cor da letra quando aparece
    }//GEN-LAST:event_botaoRelatoriosMouseEntered

    private void botaoRelatoriosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoRelatoriosMouseExited
        getBotaoRelatorios().setBackground(new Color(255, 255, 255));// Fundo Quando Solta
        getBotaoRelatorios().setForeground(new Color(0, 102, 102));// letra quando solta cor
    }//GEN-LAST:event_botaoRelatoriosMouseExited

    private void botaoVendaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoVendaMouseEntered
        getBotaoVenda().setBackground(new Color(204, 204, 204)); // cor de fundo quando aparece
        getBotaoVenda().setForeground(new Color(255, 255, 255)); // cor da letra quando aparece
    }//GEN-LAST:event_botaoVendaMouseEntered

    private void botaoVendaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoVendaMouseExited
        getBotaoVenda().setBackground(new Color(255, 255, 255));// Fundo Quando Solta
        getBotaoVenda().setForeground(new Color(0, 102, 102));// letra quando solta cor
    }//GEN-LAST:event_botaoVendaMouseExited

    private void botaoAcademiaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoAcademiaMouseEntered
        getBotaoAcademia().setBackground(new Color(204, 204, 204)); // cor de fundo quando aparece
        getBotaoAcademia().setForeground(new Color(255, 255, 255)); // cor da letra quando aparece
    }//GEN-LAST:event_botaoAcademiaMouseEntered

    private void botaoAcademiaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoAcademiaMouseExited
        getBotaoAcademia().setBackground(new Color(255, 255, 255));// Fundo Quando Solta
        getBotaoAcademia().setForeground(new Color(0, 102, 102));// letra quando solta cor
    }//GEN-LAST:event_botaoAcademiaMouseExited

    private void botaoAcademiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAcademiaActionPerformed
        Apenasnumero(getAcademia().getTxtnumero());
        getAcademia().setVisible(true);

    }//GEN-LAST:event_botaoAcademiaActionPerformed

    private void botaologoffMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaologoffMouseEntered
        getBotaologoff().setBackground(new Color(204, 204, 204)); // cor de fundo quando aparece
        getBotaologoff().setForeground(new Color(255, 255, 255)); // cor da letra quando aparece
    }//GEN-LAST:event_botaologoffMouseEntered

    private void botaologoffMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaologoffMouseExited
        getBotaologoff().setBackground(new Color(255, 255, 255));// Fundo Quando Solta
        getBotaologoff().setForeground(new Color(0, 102, 102));// letra quando solta cor
    }//GEN-LAST:event_botaologoffMouseExited

    private void botaoProfessorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoProfessorMouseEntered
        getBotaoProfessor().setBackground(new Color(204, 204, 204)); // cor de fundo quando aparece
        getBotaoProfessor().setForeground(new Color(255, 255, 255)); // cor da letra quando aparece
    }//GEN-LAST:event_botaoProfessorMouseEntered

    private void botaoProfessorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoProfessorMouseExited
        getBotaoProfessor().setBackground(new Color(255, 255, 255));// Fundo Quando Solta
        getBotaoProfessor().setForeground(new Color(0, 102, 102));// letra quando solta cor
    }//GEN-LAST:event_botaoProfessorMouseExited

    private void botaoProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoProfessorActionPerformed
        Apenasnumero(getCadastroProfessor().getTxtnumero());
        getBuscarProfessor().setVisible(true);
    }//GEN-LAST:event_botaoProfessorActionPerformed

    private void botaoAgendaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoAgendaMouseEntered
        getBotaoAgenda().setBackground(new Color(204, 204, 204)); // cor de fundo quando aparece
        getBotaoAgenda().setForeground(new Color(255, 255, 255)); // cor da letra quando aparece
    }//GEN-LAST:event_botaoAgendaMouseEntered

    private void botaoAgendaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoAgendaMouseExited
        getBotaoAgenda().setBackground(new Color(255, 255, 255));// Fundo Quando Solta
        getBotaoAgenda().setForeground(new Color(0, 102, 102));// letra quando solta cor
    }//GEN-LAST:event_botaoAgendaMouseExited

    private void botaoAgendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAgendaActionPerformed
        
        getAgendaExercicios().setVisible(true);

    }//GEN-LAST:event_botaoAgendaActionPerformed

    private void botaoSairMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoSairMouseEntered
        getBotaoSair().setBackground(new Color(204, 204, 204)); // cor de fundo quando aparece
        getBotaoSair().setForeground(new Color(255, 255, 255)); // cor da letra quando aparece
    }//GEN-LAST:event_botaoSairMouseEntered

    private void botaoSairMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoSairMouseExited
        getBotaoSair().setBackground(new Color(255, 255, 255));// Fundo Quando Solta
        getBotaoSair().setForeground(new Color(0, 102, 102));// letra quando solta cor
    }//GEN-LAST:event_botaoSairMouseExited

    private void botaoSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSairActionPerformed
        System.exit(0);

    }//GEN-LAST:event_botaoSairActionPerformed

    private void botaoDespesasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoDespesasActionPerformed
//        getDespesas().setVisible(true);
    }//GEN-LAST:event_botaoDespesasActionPerformed

    private void botaoVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVendaActionPerformed
        
    }//GEN-LAST:event_botaoVendaActionPerformed

    private void botaoAcessoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoAcessoMouseEntered
        getBotaoAcesso().setBackground(new Color(204, 204, 204)); // cor de fundo quando aparece
        getBotaoAcesso().setForeground(new Color(255, 255, 255)); // cor da letra quando aparece
    }//GEN-LAST:event_botaoAcessoMouseEntered

    private void botaoAcessoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoAcessoMouseExited
        getBotaoAcesso().setBackground(new Color(255, 255, 255));// Fundo Quando Solta
        getBotaoAcesso().setForeground(new Color(0, 102, 102));// letra quando solta cor
    }//GEN-LAST:event_botaoAcessoMouseExited

    private void botaoAcessoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAcessoActionPerformed
        
    }//GEN-LAST:event_botaoAcessoActionPerformed

    private void botaoRelatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoRelatoriosActionPerformed
        getRelatorios().setVisible(true);
    }//GEN-LAST:event_botaoRelatoriosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }
    
    public void fundos(JInternalFrame frame) {
        ((BasicInternalFrameUI) frame.getUI()).setNorthPane(null);
        frame.setBorder(null);
        getAreaPanel().add(frame);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane areaPanel;
    private javax.swing.JButton botaoAcademia;
    private javax.swing.JButton botaoAcesso;
    private javax.swing.JButton botaoAgenda;
    private javax.swing.JButton botaoAluno;
    private javax.swing.JButton botaoCaixa;
    private javax.swing.JButton botaoDespesas;
    private javax.swing.JButton botaoExercicio;
    private javax.swing.JButton botaoFornecedor;
    private javax.swing.JButton botaoFuncionario;
    private javax.swing.JButton botaoProduto;
    private javax.swing.JButton botaoProfessor;
    private javax.swing.JButton botaoRelatorios;
    private javax.swing.JButton botaoSair;
    private javax.swing.JButton botaoTarefa;
    private javax.swing.JButton botaoVenda;
    private javax.swing.JButton botaologoff;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private java.awt.Label labelfuncao;
    private java.awt.Label labelnome;
    private javax.swing.JPanel painelMenuPrincipal;
    // End of variables declaration//GEN-END:variables
    @Override
    public void actionPerformed(ActionEvent e) {
        if (e.getSource() == getBuscarFuncionario().getBotaoAdicionar()) {
            getCadastroFuncionario().getPanelLogin().setVisible(true);
        }
        if (e.getSource() == getBuscarFuncionario().getBotaoAdicionar()) {
            getCadastroFuncionario().setVisible(true);
            
        }
        if (e.getSource() == getBuscarAlunos().getBotaoAdicionar()) {
            getCadastroAlunos().setVisible(true);
            
        }
        if (e.getSource() == getBuscarProfessor().getBotaoAdicionar()) {
            getCadastroProfessor().setVisible(true);
            
        }
        if (e.getSource() == getBuscarFornecedor().getBotaoAdicionar()) {
            getCadastroFornecedor().setVisible(true);
            
        }
        if (e.getSource() == getListaAcompanhamento().getBotaoAdicionar()) {
            getAcompanhamento().setVisible(true);
            
        }
        
    }
    
    public void Ativar() {
        for (Component cp : getPainelMenuPrincipal().getComponents()) {
            cp.setEnabled(true);
        }
         getjLabel1().setEnabled(true);
         getLabelfuncao().setEnabled(true);
         getLabelnome().setEnabled(true);
    }
    
    public void Desativar() {
        for (Component cp : getPainelMenuPrincipal().getComponents()) {
            cp.setEnabled(false);
        }
         getjLabel1().setEnabled(true);
         getLabelfuncao().setEnabled(true);
         getLabelnome().setEnabled(true);
    }
    
    public void AtivarP() {
        
        getBotaoAluno().setEnabled(true);
        getBotaoProfessor().setEnabled(true);
        getBotaoAgenda().setEnabled(true);
        getBotaologoff().setEnabled(true);
        getBotaoSair().setEnabled(true);
        getBotaoAcesso().setEnabled(true);
        getBotaoExercicio().setEnabled(true);
        
    }
    
    public void Apenasnumero(JTextField numero) {
        numero.addKeyListener(new KeyAdapter() {
            @Override
            public void keyTyped(KeyEvent ev) {
                String caracteres = "0987654321";
                if (!caracteres.contains(ev.getKeyChar() + "")) {
                    ev.consume();
                }
                
            }
            
        });
        
    }
    
    public void ApenasnumeroP(JTextField numero) {
        numero.addKeyListener(new KeyAdapter() {
            @Override
            public void keyTyped(KeyEvent ev) {
                String caracteres = "0987654321.";
                if (!caracteres.contains(ev.getKeyChar() + "")) {
                    ev.consume();
                }
                
            }
            
        });
        
    }

    /**
     * @return the cadastroAlunos
     */
    public CadastroAlunos getCadastroAlunos() {
        return cadastroAlunos;
    }

    /**
     * @param cadastroAlunos the cadastroAlunos to set
     */
    public void setCadastroAlunos(CadastroAlunos cadastroAlunos) {
        this.cadastroAlunos = cadastroAlunos;
    }

    /**
     * @return the buscarAlunos
     */
    public BuscarAlunos getBuscarAlunos() {
        return buscarAlunos;
    }

    /**
     * @param buscarAlunos the buscarAlunos to set
     */
    public void setBuscarAlunos(BuscarAlunos buscarAlunos) {
        this.buscarAlunos = buscarAlunos;
    }

    /**
     * @return the buscarProfessor
     */
    public BuscarProfessor getBuscarProfessor() {
        return buscarProfessor;
    }

    /**
     * @param buscarProfessor the buscarProfessor to set
     */
    public void setBuscarProfessor(BuscarProfessor buscarProfessor) {
        this.buscarProfessor = buscarProfessor;
    }

    /**
     * @return the cadastroProfessor
     */
    public CadastroProfessor getCadastroProfessor() {
        return cadastroProfessor;
    }

    /**
     * @param cadastroProfessor the cadastroProfessor to set
     */
    public void setCadastroProfessor(CadastroProfessor cadastroProfessor) {
        this.cadastroProfessor = cadastroProfessor;
    }

    /**
     * @return the fundoPrincipal
     */
    public FundoPrincipal getFundoPrincipal() {
        return fundoPrincipal;
    }

    /**
     * @param fundoPrincipal the fundoPrincipal to set
     */
    public void setFundoPrincipal(FundoPrincipal fundoPrincipal) {
        this.fundoPrincipal = fundoPrincipal;
    }

    /**
     * @return the acompanhamento
     */
    public TelaAcompanhamento getAcompanhamento() {
        return acompanhamento;
    }

    /**
     * @param acompanhamento the acompanhamento to set
     */
    public void setAcompanhamento(TelaAcompanhamento acompanhamento) {
        this.acompanhamento = acompanhamento;
    }

    /**
     * @return the listaAcompanhamento
     */
    public ListaAcompanhamento getListaAcompanhamento() {
        return listaAcompanhamento;
    }

    /**
     * @param listaAcompanhamento the listaAcompanhamento to set
     */
    public void setListaAcompanhamento(ListaAcompanhamento listaAcompanhamento) {
        this.listaAcompanhamento = listaAcompanhamento;
    }

    /**
     * @return the exercicio
     */
    public TelaExercicio getExercicio() {
        return exercicio;
    }

    /**
     * @param exercicio the exercicio to set
     */
    public void setExercicio(TelaExercicio exercicio) {
        this.exercicio = exercicio;
    }

    /**
     * @return the academia
     */
    public TelaAcademia getAcademia() {
        return academia;
    }

    /**
     * @param academia the academia to set
     */
    public void setAcademia(TelaAcademia academia) {
        this.academia = academia;
    }

    /**
     * @return the tarefa
     */
    public TelaTarefa getTarefa() {
        return tarefa;
    }

    /**
     * @param tarefa the tarefa to set
     */
    public void setTarefa(TelaTarefa tarefa) {
        this.tarefa = tarefa;
    }

    /**
     * @return the cadastroFornecedor
     */
    public CadastroFornecedor getCadastroFornecedor() {
        return cadastroFornecedor;
    }

    /**
     * @param cadastroFornecedor the cadastroFornecedor to set
     */
    public void setCadastroFornecedor(CadastroFornecedor cadastroFornecedor) {
        this.cadastroFornecedor = cadastroFornecedor;
    }

    /**
     * @return the buscarFornecedor
     */
    public BuscarFornecedor getBuscarFornecedor() {
        return buscarFornecedor;
    }

    /**
     * @param buscarFornecedor the buscarFornecedor to set
     */
    public void setBuscarFornecedor(BuscarFornecedor buscarFornecedor) {
        this.buscarFornecedor = buscarFornecedor;
    }

    /**
     * @return the produto
     */
    public TelaProduto getProduto() {
        return produto;
    }

    /**
     * @param produto the produto to set
     */
    public void setProduto(TelaProduto produto) {
        this.produto = produto;
    }

    /**
     * @return the cadastroFuncionario
     */
    public CadastroFuncionario getCadastroFuncionario() {
        return cadastroFuncionario;
    }

    /**
     * @param cadastroFuncionario the cadastroFuncionario to set
     */
    public void setCadastroFuncionario(CadastroFuncionario cadastroFuncionario) {
        this.cadastroFuncionario = cadastroFuncionario;
    }

    /**
     * @return the buscarFuncionario
     */
    public BuscarFuncionario getBuscarFuncionario() {
        return buscarFuncionario;
    }

    /**
     * @param buscarFuncionario the buscarFuncionario to set
     */
    public void setBuscarFuncionario(BuscarFuncionario buscarFuncionario) {
        this.buscarFuncionario = buscarFuncionario;
    }

    /**
     * @return the caixa
     */
    public Caixa getCaixa() {
        return caixa;
    }

    /**
     * @param caixa the caixa to set
     */
    public void setCaixa(Caixa caixa) {
        this.caixa = caixa;
    }

    /**
     * @return the mensalidade
     */
    public Mensalidade getMensalidade() {
        return mensalidade;
    }

    /**
     * @param mensalidade the mensalidade to set
     */
    public void setMensalidade(Mensalidade mensalidade) {
        this.mensalidade = mensalidade;
    }

    /**
     * @return the agendaAluno
     */
    public AgendaSemana getAgendaAluno() {
        return agendaAluno;
    }

    /**
     * @param agendaAluno the agendaAluno to set
     */
    public void setAgendaAluno(AgendaSemana agendaAluno) {
        this.agendaAluno = agendaAluno;
    }

    /**
     * @return the agendaprofessor
     */
    public AgendaSemana getAgendaprofessor() {
        return agendaprofessor;
    }

    /**
     * @param agendaprofessor the agendaprofessor to set
     */
    public void setAgendaprofessor(AgendaSemana agendaprofessor) {
        this.agendaprofessor = agendaprofessor;
    }

    /**
     * @return the agendaExercicios
     */
    public AgendaExercicios getAgendaExercicios() {
        return agendaExercicios;
    }

    /**
     * @param agendaExercicios the agendaExercicios to set
     */
    public void setAgendaExercicios(AgendaExercicios agendaExercicios) {
        this.agendaExercicios = agendaExercicios;
    }

    /**
     * @return the listaExercicio
     */
    public ListaExercicio getListaExercicio() {
        return listaExercicio;
    }

    /**
     * @param listaExercicio the listaExercicio to set
     */
    public void setListaExercicio(ListaExercicio listaExercicio) {
        this.listaExercicio = listaExercicio;
    }

    /**
     * @return the listaMensalidades
     */
    public ListaMensalidades getListaMensalidades() {
        return listaMensalidades;
    }

    /**
     * @param listaMensalidades the listaMensalidades to set
     */
    public void setListaMensalidades(ListaMensalidades listaMensalidades) {
        this.listaMensalidades = listaMensalidades;
    }

    /**
     * @return the despesas
     */
    public Despesas getDespesas() {
        return despesas;
    }

    /**
     * @param despesas the despesas to set
     */
    public void setDespesas(Despesas despesas) {
        this.despesas = despesas;
    }

    /**
     * @return the venda
     */
    public Venda getVenda() {
        return venda;
    }

    /**
     * @param venda the venda to set
     */
    public void setVenda(Venda venda) {
        this.venda = venda;
    }

    /**
     * @return the telaSobre
     */
    public TelaSobre getTelaSobre() {
        return telaSobre;
    }

    /**
     * @param telaSobre the telaSobre to set
     */
    public void setTelaSobre(TelaSobre telaSobre) {
        this.telaSobre = telaSobre;
    }

    /**
     * @return the exerciciosTreino
     */
    public ExerciciosTreino getExerciciosTreino() {
        return exerciciosTreino;
    }

    /**
     * @param exerciciosTreino the exerciciosTreino to set
     */
    public void setExerciciosTreino(ExerciciosTreino exerciciosTreino) {
        this.exerciciosTreino = exerciciosTreino;
    }

    /**
     * @return the gerencia
     */
    public Gerencia getGerencia() {
        return gerencia;
    }

    /**
     * @param gerencia the gerencia to set
     */
    public void setGerencia(Gerencia gerencia) {
        this.gerencia = gerencia;
    }

    /**
     * @return the relatorios
     */
    public Relatorios getRelatorios() {
        return relatorios;
    }

    /**
     * @param relatorios the relatorios to set
     */
    public void setRelatorios(Relatorios relatorios) {
        this.relatorios = relatorios;
    }

    /**
     * @return the areaPanel
     */
    public javax.swing.JDesktopPane getAreaPanel() {
        return areaPanel;
    }

    /**
     * @param areaPanel the areaPanel to set
     */
    public void setAreaPanel(javax.swing.JDesktopPane areaPanel) {
        this.areaPanel = areaPanel;
    }

    /**
     * @return the botaoAcademia
     */
    public javax.swing.JButton getBotaoAcademia() {
        return botaoAcademia;
    }

    /**
     * @param botaoAcademia the botaoAcademia to set
     */
    public void setBotaoAcademia(javax.swing.JButton botaoAcademia) {
        this.botaoAcademia = botaoAcademia;
    }

    /**
     * @return the botaoAcesso
     */
    public javax.swing.JButton getBotaoAcesso() {
        return botaoAcesso;
    }

    /**
     * @param botaoAcesso the botaoAcesso to set
     */
    public void setBotaoAcesso(javax.swing.JButton botaoAcesso) {
        this.botaoAcesso = botaoAcesso;
    }

    /**
     * @return the botaoAgenda
     */
    public javax.swing.JButton getBotaoAgenda() {
        return botaoAgenda;
    }

    /**
     * @param botaoAgenda the botaoAgenda to set
     */
    public void setBotaoAgenda(javax.swing.JButton botaoAgenda) {
        this.botaoAgenda = botaoAgenda;
    }

    /**
     * @return the botaoAluno
     */
    public javax.swing.JButton getBotaoAluno() {
        return botaoAluno;
    }

    /**
     * @param botaoAluno the botaoAluno to set
     */
    public void setBotaoAluno(javax.swing.JButton botaoAluno) {
        this.botaoAluno = botaoAluno;
    }

    /**
     * @return the botaoCaixa
     */
    public javax.swing.JButton getBotaoCaixa() {
        return botaoCaixa;
    }

    /**
     * @param botaoCaixa the botaoCaixa to set
     */
    public void setBotaoCaixa(javax.swing.JButton botaoCaixa) {
        this.botaoCaixa = botaoCaixa;
    }

    /**
     * @return the botaoDespesas
     */
    public javax.swing.JButton getBotaoDespesas() {
        return botaoDespesas;
    }

    /**
     * @param botaoDespesas the botaoDespesas to set
     */
    public void setBotaoDespesas(javax.swing.JButton botaoDespesas) {
        this.botaoDespesas = botaoDespesas;
    }

    /**
     * @return the botaoExercicio
     */
    public javax.swing.JButton getBotaoExercicio() {
        return botaoExercicio;
    }

    /**
     * @param botaoExercicio the botaoExercicio to set
     */
    public void setBotaoExercicio(javax.swing.JButton botaoExercicio) {
        this.botaoExercicio = botaoExercicio;
    }

    /**
     * @return the botaoFornecedor
     */
    public javax.swing.JButton getBotaoFornecedor() {
        return botaoFornecedor;
    }

    /**
     * @param botaoFornecedor the botaoFornecedor to set
     */
    public void setBotaoFornecedor(javax.swing.JButton botaoFornecedor) {
        this.botaoFornecedor = botaoFornecedor;
    }

    /**
     * @return the botaoFuncionario
     */
    public javax.swing.JButton getBotaoFuncionario() {
        return botaoFuncionario;
    }

    /**
     * @param botaoFuncionario the botaoFuncionario to set
     */
    public void setBotaoFuncionario(javax.swing.JButton botaoFuncionario) {
        this.botaoFuncionario = botaoFuncionario;
    }

    /**
     * @return the botaoProduto
     */
    public javax.swing.JButton getBotaoProduto() {
        return botaoProduto;
    }

    /**
     * @param botaoProduto the botaoProduto to set
     */
    public void setBotaoProduto(javax.swing.JButton botaoProduto) {
        this.botaoProduto = botaoProduto;
    }

    /**
     * @return the botaoProfessor
     */
    public javax.swing.JButton getBotaoProfessor() {
        return botaoProfessor;
    }

    /**
     * @param botaoProfessor the botaoProfessor to set
     */
    public void setBotaoProfessor(javax.swing.JButton botaoProfessor) {
        this.botaoProfessor = botaoProfessor;
    }

    /**
     * @return the botaoRelatorios
     */
    public javax.swing.JButton getBotaoRelatorios() {
        return botaoRelatorios;
    }

    /**
     * @param botaoRelatorios the botaoRelatorios to set
     */
    public void setBotaoRelatorios(javax.swing.JButton botaoRelatorios) {
        this.botaoRelatorios = botaoRelatorios;
    }

    /**
     * @return the botaoSair
     */
    public javax.swing.JButton getBotaoSair() {
        return botaoSair;
    }

    /**
     * @param botaoSair the botaoSair to set
     */
    public void setBotaoSair(javax.swing.JButton botaoSair) {
        this.botaoSair = botaoSair;
    }

    /**
     * @return the botaoTarefa
     */
    public javax.swing.JButton getBotaoTarefa() {
        return botaoTarefa;
    }

    /**
     * @param botaoTarefa the botaoTarefa to set
     */
    public void setBotaoTarefa(javax.swing.JButton botaoTarefa) {
        this.botaoTarefa = botaoTarefa;
    }

    /**
     * @return the botaoVenda
     */
    public javax.swing.JButton getBotaoVenda() {
        return botaoVenda;
    }

    /**
     * @param botaoVenda the botaoVenda to set
     */
    public void setBotaoVenda(javax.swing.JButton botaoVenda) {
        this.botaoVenda = botaoVenda;
    }

    /**
     * @return the botaologoff
     */
    public javax.swing.JButton getBotaologoff() {
        return botaologoff;
    }

    /**
     * @param botaologoff the botaologoff to set
     */
    public void setBotaologoff(javax.swing.JButton botaologoff) {
        this.botaologoff = botaologoff;
    }

    /**
     * @return the jLabel1
     */
    public javax.swing.JLabel getjLabel1() {
        return jLabel1;
    }

    /**
     * @param jLabel1 the jLabel1 to set
     */
    public void setjLabel1(javax.swing.JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    /**
     * @return the jPanel1
     */
    public javax.swing.JPanel getjPanel1() {
        return jPanel1;
    }

    /**
     * @param jPanel1 the jPanel1 to set
     */
    public void setjPanel1(javax.swing.JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    /**
     * @return the jPanel3
     */
    public javax.swing.JPanel getjPanel3() {
        return jPanel3;
    }

    /**
     * @param jPanel3 the jPanel3 to set
     */
    public void setjPanel3(javax.swing.JPanel jPanel3) {
        this.jPanel3 = jPanel3;
    }

    /**
     * @return the labelfuncao
     */
    public java.awt.Label getLabelfuncao() {
        return labelfuncao;
    }

    /**
     * @param labelfuncao the labelfuncao to set
     */
    public void setLabelfuncao(java.awt.Label labelfuncao) {
        this.labelfuncao = labelfuncao;
    }

    /**
     * @return the labelnome
     */
    public java.awt.Label getLabelnome() {
        return labelnome;
    }

    /**
     * @param labelnome the labelnome to set
     */
    public void setLabelnome(java.awt.Label labelnome) {
        this.labelnome = labelnome;
    }

    /**
     * @return the painelMenuPrincipal
     */
    public javax.swing.JPanel getPainelMenuPrincipal() {
        return painelMenuPrincipal;
    }

    /**
     * @param painelMenuPrincipal the painelMenuPrincipal to set
     */
    public void setPainelMenuPrincipal(javax.swing.JPanel painelMenuPrincipal) {
        this.painelMenuPrincipal = painelMenuPrincipal;
    }

   
    
}
