/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.pbd.view;

import java.awt.Color;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JTextField;

/**
 *
 * @author Glenda Alves de Lima
 */
public class Venda extends javax.swing.JInternalFrame {

    /**
     * Creates new form Venda
     */
    private Icon Iconexcluir, Iconeditar,IconeAd;
    private JButton btnEx, btnEd,btnad;

    public Venda() {
        initComponents();
        Iconexcluir = new ImageIcon(getClass().getResource("/br/com/pbd/resource/removerC.png"));
        Iconeditar = new ImageIcon(getClass().getResource("/br/com/pbd/resource/editarr.png"));
        IconeAd = new ImageIcon(getClass().getResource("/br/com/pbd/resource/adicionarC.png"));
        
        btnEx = new JButton(Iconexcluir);
        btnEx.setName("Excluir");
        btnEx.setBorder(null);
        btnEx.setContentAreaFilled(false);
        
        btnEd = new JButton(Iconeditar);
        btnEd.setName("Editar");
        btnEd.setBorder(null);
        btnEd.setContentAreaFilled(false);
        
        btnad = new JButton(IconeAd);
        btnad.setName("Adicionar");
        btnad.setBorder(null);
        btnad.setContentAreaFilled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        labelcadastro2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        botaoAdicionarprodutos = new javax.swing.JButton();
        botaoFechar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaprodutosvenda = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        valorsubtotal = new br.com.pbd.modelos.JTextFieldHint(new JTextField(), "simbolo", "0.00");
        valordesconto = new br.com.pbd.modelos.JTextFieldHint(new JTextField(), "simbolo", "0.00");
        valortotal = new br.com.pbd.modelos.JTextFieldHint(new JTextField(), "simbolo", "0.00");
        botaocancelarvenda = new javax.swing.JButton();
        botaofinalizarvenda = new javax.swing.JButton();

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setPreferredSize(new java.awt.Dimension(962, 739));

        jPanel11.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 9, Short.MAX_VALUE)
        );

        labelcadastro2.setFont(new java.awt.Font("Felix Titling", 0, 24)); // NOI18N
        labelcadastro2.setForeground(new java.awt.Color(0, 102, 102));
        labelcadastro2.setText("Venda");

        jPanel5.setBackground(new java.awt.Color(153, 153, 153));

        jLabel2.setFont(new java.awt.Font("DeVinne Txt BT", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Produtos Adicionados");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 0, 0))
        );

        botaoAdicionarprodutos.setBackground(new java.awt.Color(255, 255, 255));
        botaoAdicionarprodutos.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        botaoAdicionarprodutos.setForeground(new java.awt.Color(0, 102, 102));
        botaoAdicionarprodutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/pbd/resource/Aproduto.png"))); // NOI18N
        botaoAdicionarprodutos.setText("Adicionar Produtos");
        botaoAdicionarprodutos.setBorderPainted(false);
        botaoAdicionarprodutos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botaoAdicionarprodutosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botaoAdicionarprodutosMouseExited(evt);
            }
        });
        botaoAdicionarprodutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAdicionarprodutosActionPerformed(evt);
            }
        });

        botaoFechar.setBackground(new java.awt.Color(255, 255, 255));
        botaoFechar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        botaoFechar.setForeground(new java.awt.Color(0, 102, 102));
        botaoFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/pbd/resource/Cancela.png"))); // NOI18N
        botaoFechar.setText("Fechar");
        botaoFechar.setBorderPainted(false);
        botaoFechar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botaoFecharMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botaoFecharMouseExited(evt);
            }
        });
        botaoFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoFecharActionPerformed(evt);
            }
        });

        tabelaprodutosvenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tabelaprodutosvenda.setRowHeight(30);
        jScrollPane1.setViewportView(tabelaprodutosvenda);

        jPanel3.setBackground(new java.awt.Color(255, 255, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        label1.setForeground(new java.awt.Color(0, 0, 0));
        label1.setText("SubTotal  :");

        label2.setForeground(new java.awt.Color(0, 0, 0));
        label2.setText("Desconto :");

        label3.setForeground(new java.awt.Color(0, 0, 0));
        label3.setText("Valor Total :");

        valorsubtotal.setBackground(new java.awt.Color(255, 255, 204));
        valorsubtotal.setFont(new java.awt.Font("Felix Titling", 0, 24)); // NOI18N
        valorsubtotal.setEnabled(false);
        valorsubtotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valorsubtotalActionPerformed(evt);
            }
        });

        valordesconto.setBackground(new java.awt.Color(255, 255, 204));
        valordesconto.setFont(new java.awt.Font("Felix Titling", 0, 24)); // NOI18N
        valordesconto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valordescontoActionPerformed(evt);
            }
        });

        valortotal.setBackground(new java.awt.Color(255, 255, 204));
        valortotal.setFont(new java.awt.Font("Felix Titling", 0, 24)); // NOI18N
        valortotal.setEnabled(false);
        valortotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valortotalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valorsubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valordesconto, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valortotal, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(valorsubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(valordesconto, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(valortotal, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        botaocancelarvenda.setBackground(new java.awt.Color(255, 255, 255));
        botaocancelarvenda.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        botaocancelarvenda.setForeground(new java.awt.Color(0, 102, 102));
        botaocancelarvenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/pbd/resource/excluirVenda.png"))); // NOI18N
        botaocancelarvenda.setText("Cancelar Venda");
        botaocancelarvenda.setBorderPainted(false);
        botaocancelarvenda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botaocancelarvendaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botaocancelarvendaMouseExited(evt);
            }
        });
        botaocancelarvenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaocancelarvendaActionPerformed(evt);
            }
        });

        botaofinalizarvenda.setBackground(new java.awt.Color(255, 255, 255));
        botaofinalizarvenda.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        botaofinalizarvenda.setForeground(new java.awt.Color(0, 102, 102));
        botaofinalizarvenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/pbd/resource/FinalizarVenda.png"))); // NOI18N
        botaofinalizarvenda.setText("Realizar Venda");
        botaofinalizarvenda.setBorderPainted(false);
        botaofinalizarvenda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botaofinalizarvendaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botaofinalizarvendaMouseExited(evt);
            }
        });
        botaofinalizarvenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaofinalizarvendaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(168, 168, 168)
                .addComponent(botaoAdicionarprodutos)
                .addGap(18, 18, 18)
                .addComponent(botaofinalizarvenda, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(botaocancelarvenda)
                .addGap(32, 32, 32)
                .addComponent(botaoFechar)
                .addGap(32, 32, 32))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(labelcadastro2)
                        .addGap(0, 866, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelcadastro2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoFechar)
                    .addComponent(botaocancelarvenda)
                    .addComponent(botaoAdicionarprodutos)
                    .addComponent(botaofinalizarvenda))
                .addGap(20, 20, 20)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoAdicionarprodutosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoAdicionarprodutosMouseEntered
        getBotaoAdicionarprodutos().setBackground(new Color(204, 204, 204)); // cor de fundo quando aparece
        getBotaoAdicionarprodutos().setForeground(new Color(255, 255, 255)); // cor da letra quando aparece
    }//GEN-LAST:event_botaoAdicionarprodutosMouseEntered

    private void botaoAdicionarprodutosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoAdicionarprodutosMouseExited
        getBotaoAdicionarprodutos().setBackground(new Color(255, 255, 255));// Fundo Quando Solta
        getBotaoAdicionarprodutos().setForeground(new Color(0, 102, 102));// letra quando solta cor
    }//GEN-LAST:event_botaoAdicionarprodutosMouseExited

    private void botaoAdicionarprodutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAdicionarprodutosActionPerformed

    }//GEN-LAST:event_botaoAdicionarprodutosActionPerformed

    private void botaoFecharMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoFecharMouseEntered
        getBotaoFechar().setBackground(new Color(204, 204, 204)); // cor de fundo quando aparece
        getBotaoFechar().setForeground(new Color(255, 255, 255)); // cor da letra quando aparece
    }//GEN-LAST:event_botaoFecharMouseEntered

    private void botaoFecharMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoFecharMouseExited
        getBotaoFechar().setBackground(new Color(255, 255, 255));// Fundo Quando Solta
        getBotaoFechar().setForeground(new Color(0, 102, 102));// letra quando solta cor
    }//GEN-LAST:event_botaoFecharMouseExited

    private void botaoFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoFecharActionPerformed
        setVisible(false);
    }//GEN-LAST:event_botaoFecharActionPerformed

    private void botaocancelarvendaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaocancelarvendaMouseEntered
        getBotaocancelarvenda().setBackground(new Color(204, 204, 204)); // cor de fundo quando aparece
        getBotaocancelarvenda().setForeground(new Color(255, 255, 255)); // cor da letra quando aparece
    }//GEN-LAST:event_botaocancelarvendaMouseEntered

    private void botaocancelarvendaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaocancelarvendaMouseExited
        getBotaocancelarvenda().setBackground(new Color(255, 255, 255));// Fundo Quando Solta
        getBotaocancelarvenda().setForeground(new Color(0, 102, 102));// letra quando solta cor
    }//GEN-LAST:event_botaocancelarvendaMouseExited

    private void botaocancelarvendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaocancelarvendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaocancelarvendaActionPerformed

    private void botaofinalizarvendaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaofinalizarvendaMouseEntered
        getBotaofinalizarvenda().setBackground(new Color(204, 204, 204)); // cor de fundo quando aparece
        getBotaofinalizarvenda().setForeground(new Color(255, 255, 255)); // cor da letra quando aparece
    }//GEN-LAST:event_botaofinalizarvendaMouseEntered

    private void botaofinalizarvendaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaofinalizarvendaMouseExited
        getBotaofinalizarvenda().setBackground(new Color(255, 255, 255));// Fundo Quando Solta
        getBotaofinalizarvenda().setForeground(new Color(0, 102, 102));// letra quando solta cor
    }//GEN-LAST:event_botaofinalizarvendaMouseExited

    private void botaofinalizarvendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaofinalizarvendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaofinalizarvendaActionPerformed

    private void valorsubtotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valorsubtotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valorsubtotalActionPerformed

    private void valordescontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valordescontoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valordescontoActionPerformed

    private void valortotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valortotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valortotalActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoAdicionarprodutos;
    private javax.swing.JButton botaoFechar;
    private javax.swing.JButton botaocancelarvenda;
    private javax.swing.JButton botaofinalizarvenda;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private javax.swing.JLabel labelcadastro2;
    private javax.swing.JTable tabelaprodutosvenda;
    private javax.swing.JTextField valordesconto;
    private javax.swing.JTextField valorsubtotal;
    private javax.swing.JTextField valortotal;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the botaoAdicionarprodutos
     */
    public javax.swing.JButton getBotaoAdicionarprodutos() {
        return botaoAdicionarprodutos;
    }

    /**
     * @param botaoAdicionarprodutos the botaoAdicionarprodutos to set
     */
    public void setBotaoAdicionarprodutos(javax.swing.JButton botaoAdicionarprodutos) {
        this.botaoAdicionarprodutos = botaoAdicionarprodutos;
    }

    /**
     * @return the botaoFechar
     */
    public javax.swing.JButton getBotaoFechar() {
        return botaoFechar;
    }

    /**
     * @param botaoFechar the botaoFechar to set
     */
    public void setBotaoFechar(javax.swing.JButton botaoFechar) {
        this.botaoFechar = botaoFechar;
    }

    /**
     * @return the botaocancelarvenda
     */
    public javax.swing.JButton getBotaocancelarvenda() {
        return botaocancelarvenda;
    }

    /**
     * @param botaocancelarvenda the botaocancelarvenda to set
     */
    public void setBotaocancelarvenda(javax.swing.JButton botaocancelarvenda) {
        this.botaocancelarvenda = botaocancelarvenda;
    }

    /**
     * @return the botaofinalizarvenda
     */
    public javax.swing.JButton getBotaofinalizarvenda() {
        return botaofinalizarvenda;
    }

    /**
     * @param botaofinalizarvenda the botaofinalizarvenda to set
     */
    public void setBotaofinalizarvenda(javax.swing.JButton botaofinalizarvenda) {
        this.botaofinalizarvenda = botaofinalizarvenda;
    }

    /**
     * @return the jLabel2
     */
    public javax.swing.JLabel getjLabel2() {
        return jLabel2;
    }

    /**
     * @param jLabel2 the jLabel2 to set
     */
    public void setjLabel2(javax.swing.JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }

    /**
     * @return the jPanel11
     */
    public javax.swing.JPanel getjPanel11() {
        return jPanel11;
    }

    /**
     * @param jPanel11 the jPanel11 to set
     */
    public void setjPanel11(javax.swing.JPanel jPanel11) {
        this.jPanel11 = jPanel11;
    }

    /**
     * @return the jPanel3
     */
    public javax.swing.JPanel getjPanel3() {
        return jPanel3;
    }

    /**
     * @param jPanel3 the jPanel3 to set
     */
    public void setjPanel3(javax.swing.JPanel jPanel3) {
        this.jPanel3 = jPanel3;
    }

    /**
     * @return the jPanel4
     */
    public javax.swing.JPanel getjPanel4() {
        return jPanel4;
    }

    /**
     * @param jPanel4 the jPanel4 to set
     */
    public void setjPanel4(javax.swing.JPanel jPanel4) {
        this.jPanel4 = jPanel4;
    }

    /**
     * @return the jPanel5
     */
    public javax.swing.JPanel getjPanel5() {
        return jPanel5;
    }

    /**
     * @param jPanel5 the jPanel5 to set
     */
    public void setjPanel5(javax.swing.JPanel jPanel5) {
        this.jPanel5 = jPanel5;
    }

    /**
     * @return the jScrollPane1
     */
    public javax.swing.JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    /**
     * @param jScrollPane1 the jScrollPane1 to set
     */
    public void setjScrollPane1(javax.swing.JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    /**
     * @return the label1
     */
    public java.awt.Label getLabel1() {
        return label1;
    }

    /**
     * @param label1 the label1 to set
     */
    public void setLabel1(java.awt.Label label1) {
        this.label1 = label1;
    }

    /**
     * @return the label2
     */
    public java.awt.Label getLabel2() {
        return label2;
    }

    /**
     * @param label2 the label2 to set
     */
    public void setLabel2(java.awt.Label label2) {
        this.label2 = label2;
    }

    /**
     * @return the label3
     */
    public java.awt.Label getLabel3() {
        return label3;
    }

    /**
     * @param label3 the label3 to set
     */
    public void setLabel3(java.awt.Label label3) {
        this.label3 = label3;
    }

    /**
     * @return the labelcadastro2
     */
    public javax.swing.JLabel getLabelcadastro2() {
        return labelcadastro2;
    }

    /**
     * @param labelcadastro2 the labelcadastro2 to set
     */
    public void setLabelcadastro2(javax.swing.JLabel labelcadastro2) {
        this.labelcadastro2 = labelcadastro2;
    }

    /**
     * @return the tabelaprodutosvenda
     */
    public javax.swing.JTable getTabelaprodutosvenda() {
        return tabelaprodutosvenda;
    }

    /**
     * @param tabelaprodutosvenda the tabelaprodutosvenda to set
     */
    public void setTabelaprodutosvenda(javax.swing.JTable tabelaprodutosvenda) {
        this.tabelaprodutosvenda = tabelaprodutosvenda;
    }

    /**
     * @return the valordesconto
     */
    public javax.swing.JTextField getValordesconto() {
        return valordesconto;
    }

    /**
     * @param valordesconto the valordesconto to set
     */
    public void setValordesconto(javax.swing.JTextField valordesconto) {
        this.valordesconto = valordesconto;
    }

    /**
     * @return the valorsubtotal
     */
    public javax.swing.JTextField getValorsubtotal() {
        return valorsubtotal;
    }

    /**
     * @param valorsubtotal the valorsubtotal to set
     */
    public void setValorsubtotal(javax.swing.JTextField valorsubtotal) {
        this.valorsubtotal = valorsubtotal;
    }

    /**
     * @return the valortotal
     */
    public javax.swing.JTextField getValortotal() {
        return valortotal;
    }

    /**
     * @param valortotal the valortotal to set
     */
    public void setValortotal(javax.swing.JTextField valortotal) {
        this.valortotal = valortotal;
    }

    /**
     * @return the btnEx
     */
    public JButton getBtnEx() {
        return btnEx;
    }

    /**
     * @return the btnEd
     */
    public JButton getBtnEd() {
        return btnEd;
    }

    /**
     * @return the btnad
     */
    public JButton getBtnad() {
        return btnad;
    }

}
